'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';
import {requireSafeWebUrl} from '@/lib/url';

async function context(){const db=await createClient();const {data}=await db.auth.getClaims();const userId=data?.claims?.sub;if(!userId)throw new Error('请重新登录');const {data:admin}=await db.from('admin_users').select('role,is_active').eq('user_id',userId).maybeSingle();if(!admin?.is_active||!['admin','editor'].includes(admin.role))throw new Error('没有后台操作权限');return {db,userId}}
const scores={urgency:{'紧急':100,'重要':75,'普通':45,'低':20},required:{'必做':100,'建议':70,'可做':40,'不推荐':10}} as const;
export async function saveTask(input:{id?:string;title:string;url:string;quick:string;description?:string;category:string;urgency:keyof typeof scores.urgency;required:keyof typeof scores.required;minutes:number;deadline?:string;audience:string;pinned:boolean;daily:boolean;multi:boolean;history:boolean;leader:boolean;push:boolean;status:'draft'|'published'}){requireSafeWebUrl(input.url,'任务外链');const {db,userId}=await context();const id=input.id??crypto.randomUUID();const row={id,title:input.title.trim(),external_url:input.url,quick_instruction:input.quick.trim(),description:input.description||null,category:input.category,urgency_score:scores.urgency[input.urgency],required_score:scores.required[input.required],estimated_minutes:input.minutes,deadline:input.deadline||null,audience:input.audience,is_pinned:input.pinned,show_in_daily:input.daily,is_multi_account:input.multi,count_completion:input.history,leaderboard_enabled:input.leader,push_reserved:input.push,status:input.status,created_by:userId};if(input.pinned){const {error}=await db.from('tasks').update({is_pinned:false}).neq('id',id);if(error)throw new Error('置顶任务更新失败')}const query=input.id?db.from('tasks').update(row).eq('id',id):db.from('tasks').insert(row);const {error}=await query;if(error)throw new Error('任务保存失败');revalidatePath('/admin/tasks');revalidatePath('/urgent');revalidatePath('/daily')}
export async function setTaskStatus(id:string,status:'published'|'offline'){const {db}=await context();const {error}=await db.from('tasks').update({status}).eq('id',id);if(error)throw new Error('任务状态更新失败');revalidatePath('/admin/tasks');revalidatePath('/urgent');revalidatePath('/daily')}
export async function renameTask(id:string,title:string){if(!title.trim())throw new Error('任务标题不能为空');const {db}=await context();const {error}=await db.from('tasks').update({title:title.trim()}).eq('id',id);if(error)throw new Error('任务更新失败');revalidatePath('/admin/tasks');revalidatePath('/urgent');revalidatePath('/daily')}
export async function deleteTask(id:string){const {db}=await context();const {error}=await db.from('tasks').delete().eq('id',id);if(error)throw new Error('任务删除失败');revalidatePath('/admin/tasks');revalidatePath('/urgent');revalidatePath('/daily')}
export async function duplicateTask(id:string){const {db,userId}=await context();const {data,error}=await db.from('tasks').select('*').eq('id',id).single();if(error||!data)throw new Error('复制失败');const {id:_id,created_at:_created,updated_at:_updated,...copy}=data;void _id;void _created;void _updated;const result=await db.from('tasks').insert({...copy,title:`${copy.title}（副本）`,status:'draft',created_by:userId});if(result.error)throw new Error('复制失败');revalidatePath('/admin/tasks')}
type Domain='quick_links'|'text_templates'|'media_items'|'guides';
export async function deleteContent(domain:Domain,id:string){const {db}=await context();const {error}=await db.from(domain).delete().eq('id',id);if(error)throw new Error('删除失败');revalidatePath('/admin');revalidatePath('/guide');revalidatePath('/guide/tools');revalidatePath('/media')}
export async function updateContent(domain:Domain,id:string,values:Record<string,unknown>){for(const key of ['external_url','cover_url'])if(typeof values[key]==='string')requireSafeWebUrl(values[key] as string,key,key==='cover_url');const {db}=await context();const {error}=await db.from(domain).update(values).eq('id',id);if(error)throw new Error('更新失败');revalidatePath('/admin');revalidatePath('/guide');revalidatePath('/guide/tools');revalidatePath('/media')}
export async function createContent(domain:Domain,values:Record<string,unknown>){for(const key of ['external_url','cover_url'])if(typeof values[key]==='string')requireSafeWebUrl(values[key] as string,key,key==='cover_url');const {db}=await context();const {error}=await db.from(domain).insert(values);if(error)throw new Error('新增失败');revalidatePath('/admin');revalidatePath('/guide');revalidatePath('/guide/tools');revalidatePath('/media')}
export async function saveVisualSetting(values:{module_key:string;background_url:string;use_custom_background:boolean;background_position:string;background_size:string;overlay_opacity:number;decorative_text:string;show_decorative_text:boolean}){requireSafeWebUrl(values.background_url,'背景图片',true);const {db}=await context();const {error}=await db.from('visual_settings').upsert(values,{onConflict:'module_key'});if(error)throw new Error('视觉设置保存失败');revalidatePath('/admin/visual-settings');revalidatePath('/urgent');revalidatePath('/daily');revalidatePath('/media');revalidatePath('/guide');revalidatePath('/me')}
