'use client';
import {useRef,useState,useTransition} from 'react';
import {logout,updateLeaderboardOptIn,updateNickname,updatePlatformAccountCount} from '@/app/user-actions';
import {AvatarUpload} from '@/components/AvatarUpload';
import {PLATFORMS,type Platform} from '@/lib/platforms';

type AccountCount={platform:string;account_count:number};

export function AccountForm({userId,avatarUrl,email,nickname,leaderboardOptIn,accounts}:{userId:string;avatarUrl:string|null;email:string;nickname:string;leaderboardOptIn:boolean;accounts:AccountCount[]}){
  const initial=Object.fromEntries(PLATFORMS.map(platform=>[platform,accounts.find(row=>row.platform===platform)?.account_count??null])) as Record<Platform,number|null>;
  const [value,setValue]=useState(nickname),[publicRank,setPublicRank]=useState(leaderboardOptIn),[counts,setCounts]=useState(initial);const [notice,setNotice]=useState(''),[accountErrors,setAccountErrors]=useState<Partial<Record<Platform,string>>>({});const [pending,start]=useTransition();
  const confirmed=useRef(initial),desired=useRef(initial),saving=useRef(Object.fromEntries(PLATFORMS.map(platform=>[platform,false])) as Record<Platform,boolean>);
  const saveLatest=async(platform:Platform)=>{if(saving.current[platform])return;saving.current[platform]=true;try{while(true){const target=desired.current[platform];try{const saved=await updatePlatformAccountCount(platform,target);confirmed.current[platform]=saved;if(desired.current[platform]===target){desired.current[platform]=saved;setCounts(state=>({...state,[platform]:saved}));setNotice(`${platform}账号数量已保存`);break}}catch{const rollback=confirmed.current[platform];desired.current[platform]=rollback;setCounts(state=>({...state,[platform]:rollback}));setAccountErrors(state=>({...state,[platform]:'账号数量保存失败，请重试'}));break}}}finally{saving.current[platform]=false}};
  const adjust=(platform:Platform,delta:-1|1)=>{const current=desired.current[platform];const next=delta===1?Math.min(10000,(current??0)+1):current===null||current<=1?null:current-1;if(next===current)return;desired.current[platform]=next;setCounts(state=>({...state,[platform]:next}));setAccountErrors(state=>({...state,[platform]:undefined}));void saveLatest(platform)};
  return <div className="space-y-4"><AvatarUpload userId={userId} avatarUrl={avatarUrl}/><label className="field">邮箱<input value={email} disabled/></label><label className="field">昵称<input required maxLength={40} value={value} onChange={e=>setValue(e.target.value)}/></label><section className="rounded-2xl border border-[#e2edf5] p-4"><h2 className="m-0 text-sm">平台账号数量</h2><p className="mb-3 mt-1 text-xs leading-5 text-[#8298ac]">每个平台独立设置；未使用的平台无需配置。</p><div className="divide-y divide-[#edf2f6]">{PLATFORMS.map(platform=><div key={platform} className="py-3"><div className="flex items-center justify-between"><b className="text-sm">{platform}</b><div className="flex items-center gap-3"><button type="button" aria-label={`减少${platform}账号数量`} disabled={counts[platform]===null} onClick={()=>adjust(platform,-1)} className="h-8 w-8 rounded-full border border-[#dbeaf4] bg-white text-lg disabled:opacity-40">−</button><span className="min-w-12 text-center text-sm font-bold">{counts[platform]??'未设置'}</span><button type="button" aria-label={`增加${platform}账号数量`} onClick={()=>adjust(platform,1)} className="h-8 w-8 rounded-full border-0 bg-[#eaf5fc] text-lg text-[#3785cc] disabled:opacity-40">＋</button></div></div>{accountErrors[platform]&&<p className="mb-0 mt-1 text-right text-[10px] text-red-500">{accountErrors[platform]}</p>}</div>)}</div></section><label className="flex items-center justify-between text-sm"><span>参与养渝英雄榜</span><input type="checkbox" checked={publicRank} onChange={e=>{const enabled=e.target.checked;setPublicRank(enabled);start(async()=>{try{await updateLeaderboardOptIn(enabled);setNotice('英雄榜设置已保存')}catch(error){setPublicRank(!enabled);setNotice(error instanceof Error?error.message:'保存失败')}})}}/></label><p className="text-xs leading-5 text-[#8298ac]">开启后，榜单仅展示昵称、头像、名次和行动次数。</p>{notice&&<p className="text-sm text-[#438bd1]">{notice}</p>}<button disabled={pending} className="primary w-full" onClick={()=>start(async()=>{try{await updateNickname(value);setNotice('昵称已保存')}catch(error){setNotice(error instanceof Error?error.message:'保存失败')}})}>保存昵称</button><button disabled={pending} className="w-full rounded-xl border border-[#d8e8f3] bg-white py-3 font-bold text-[#58738d]" onClick={()=>start(()=>logout())}>退出登录</button></div>
}
