'use client';
import {useState,useTransition} from 'react';
import {changeAdminAccountRole,createAdminAccount,setAdminAccountActive} from '@/app/admin/user-actions';
import type {AdminAccount} from '@/lib/admin-users';
import {AdminCard,AdminShell,StatusTag,Toggle} from './AdminShell';

const createdDate=(value:string)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));

export function AdminUserManagement({initialAccounts,initialError}:{initialAccounts:AdminAccount[];initialError?:string}){
  const [accounts,setAccounts]=useState(initialAccounts),[creating,setCreating]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<'admin'|'editor'>('editor'),[isActive,setIsActive]=useState(true),[message,setMessage]=useState(initialError??''),[pending,start]=useTransition();
  const replace=(account:{userId:string;role:'admin'|'editor';isActive:boolean})=>setAccounts(current=>current.map(item=>item.userId===account.userId?{...item,...account}:item));
  const create=(event:React.FormEvent)=>{event.preventDefault();if(pending)return;setMessage('');start(async()=>{const result=await createAdminAccount({email,password,role,isActive});if(!result.ok){setMessage(result.error);return}setAccounts(current=>[...current,result.data]);setEmail('');setPassword('');setRole('editor');setIsActive(true);setCreating(false);setMessage(result.message)})};
  const changeRole=(userId:string,nextRole:'admin'|'editor')=>{setMessage('');start(async()=>{const result=await changeAdminAccountRole(userId,nextRole);if(!result.ok){setMessage(result.error);return}replace(result.data);setMessage(result.message)})};
  const toggleActive=(account:AdminAccount)=>{setMessage('');start(async()=>{const result=await setAdminAccountActive(account.userId,!account.isActive);if(!result.ok){setMessage(result.error);return}replace(result.data);setMessage(result.message)})};
  const actions=(account:AdminAccount)=><><select aria-label={`${account.email} 的角色`} value={account.role} disabled={pending} onChange={event=>changeRole(account.userId,event.target.value as 'admin'|'editor')}><option value="admin">admin</option><option value="editor">editor</option></select><button disabled={pending} onClick={()=>toggleActive(account)}>{account.isActive?'停用':'启用'}</button></>;
  return <AdminShell title="用户管理" subtitle="管理可登录后台的管理员与编辑账号"><AdminCard><div className="manager-toolbar"><div><h2>后台账号</h2></div><button disabled={pending||Boolean(initialError)} onClick={()=>setCreating(value=>!value)}>＋ 新增后台账号</button></div>{creating&&<form className="admin-account-form" onSubmit={create}><label className="admin-field"><span>邮箱 *</span><input type="email" autoComplete="off" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label className="admin-field"><span>初始密码 *</span><input type="password" autoComplete="new-password" minLength={8} maxLength={128} required value={password} onChange={event=>setPassword(event.target.value)}/></label><label className="admin-field"><span>角色 *</span><select value={role} onChange={event=>setRole(event.target.value as 'admin'|'editor')}><option value="editor">editor</option><option value="admin">admin</option></select></label><Toggle label="是否启用" checked={isActive} onChange={setIsActive}/><div className="admin-account-form-actions"><button type="button" className="outline-button" onClick={()=>setCreating(false)}>取消</button><button className="publish-button" disabled={pending}>{pending?'创建中…':'创建账号'}</button></div></form>}{message&&<p className="admin-inline-message" role="status">{message}</p>}<div className="table-scroll"><table className="admin-table"><thead><tr><th>邮箱</th><th>角色</th><th>状态</th><th>创建日期</th><th>操作</th></tr></thead><tbody>{accounts.map(account=><tr key={account.userId}><td><b>{account.email}</b></td><td>{account.role}</td><td><StatusTag tone={account.isActive?'green':'gray'}>{account.isActive?'启用':'停用'}</StatusTag></td><td>{createdDate(account.createdAt)}</td><td className="admin-account-actions">{actions(account)}</td></tr>)}</tbody></table></div><div className="admin-account-mobile">{accounts.map(account=><article key={account.userId}><div><b>{account.email}</b><small>{createdDate(account.createdAt)}</small></div><StatusTag tone={account.isActive?'green':'gray'}>{account.isActive?'启用':'停用'}</StatusTag><div className="admin-account-actions">{actions(account)}</div></article>)}</div>{!accounts.length&&!message&&<p className="muted">暂无后台账号</p>}</AdminCard></AdminShell>;
}
