'use client';
import Link from 'next/link';import {usePathname} from 'next/navigation';import {useState} from 'react';
const nav=[['⌂','后台首页','/admin'],['⊞','发布任务','/admin/tasks/new'],['▣','任务管理','/admin/tasks'],['⌘','快捷入口管理','/admin/quick-links'],['▰','模板 / 尾巴管理','/admin/templates'],['▧','物料管理','/admin/media'],['▤','攻略 & Tips','/admin/guides'],['▥','英雄榜管理','/admin/leaderboard'],['♟','用户管理','/admin/users'],['◉','视觉设置','/admin/visual-settings'],['⚙','系统设置','/admin/settings']];
export function AdminShell({children,title,subtitle,utility}:{children:React.ReactNode;title:string;subtitle?:string;utility?:React.ReactNode}){const path=usePathname();const [menu,setMenu]=useState(false);const active=(href:string)=>href==='/admin'||href==='/admin/tasks'||href==='/admin/tasks/new'?path===href:path===href||path.startsWith(`${href}/`);return <main className="admin-shell-v2"><aside className={`admin-sidebar ${menu?'is-open':''}`}><div className="admin-brand"><b>梓渝</b><span>极速行动站 · 后台管理</span></div><nav>{nav.map(([icon,label,href])=><Link key={href} href={href} onClick={()=>setMenu(false)} className={active(href)?'active':''}><i>{icon}</i><span>{label}</span></Link>)}</nav><div className="admin-side-note"><strong>把喜欢，<br/>变成行动。</strong><small>ZIYU<br/>MORE FOR A<br/>BRIGHTER TOMORROW.</small></div></aside>{menu&&<button aria-label="关闭菜单" className="admin-menu-scrim" onClick={()=>setMenu(false)}/>}<section className="admin-stage"><header className="admin-topbar"><button className="admin-menu-button" onClick={()=>setMenu(true)} aria-label="打开菜单">☰</button><div className="admin-top-copy"><strong>{title}</strong>{subtitle&&<span>{subtitle}</span>}</div><div className="admin-user"><span>♧</span><b>Y</b><strong>管理员⌄</strong></div></header><div className={`admin-content ${utility?'has-utility':''}`}><div className="admin-workspace">{children}</div>{utility&&<aside className="admin-utility">{utility}</aside>}</div></section></main>}

export function AdminCard({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`admin-card-v2 ${className}`}>{children}</section>}
export function StatusTag({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'red'|'green'|'gold'|'purple'|'gray'}){return <span className={`status-tag ${tone}`}>{children}</span>}
export function Toggle({checked,onChange,label}:{checked:boolean;onChange?:(v:boolean)=>void;label?:string}){return <label className="admin-toggle">{label&&<span>{label}</span>}<input type="checkbox" checked={checked} onChange={e=>onChange?.(e.target.checked)}/><i/></label>}
export function ChoiceChips({items,value,onChange,tone='blue'}:{items:string[];value:string;onChange:(v:string)=>void;tone?:string}){return <div className="admin-chips">{items.map(item=><button type="button" key={item} onClick={()=>onChange(item)} className={`${value===item?'selected':''} ${tone}`}>{item}</button>)}</div>}
