import {createClient} from '@/lib/supabase/server';
import type {Category,Guide,MediaItem,QuickLink,Task,TextTemplate,VisualSetting} from './types';

export class ContentDataError extends Error{constructor(){super('内容暂时无法加载，请稍后重试。')}}
type TaskRow={id:string;title:string;description:string|null;category:string;platform:string|null;external_url:string;quick_instruction:string;urgency_score:number;required_score:number;estimated_minutes:number;deadline:string|null;created_at:string;is_pinned:boolean;show_in_daily:boolean;is_multi_account:boolean;sort_order:number;task_steps?:{step_number:number;content:string}[]};
const mapTask=(row:TaskRow):Task=>({id:row.id,title:row.title,description:row.description??'',category:row.category as Category,platform:row.platform??'',url:row.external_url,quick:row.quick_instruction,urgency:row.urgency_score,required:row.required_score,minutes:row.estimated_minutes,deadline:row.deadline,createdAt:row.created_at,pinned:row.is_pinned,daily:row.show_in_daily,multi:row.is_multi_account,progress:0,goal:12,steps:[...(row.task_steps??[])].sort((a,b)=>a.step_number-b.step_number).map(x=>x.content)});
async function run<T>(query:PromiseLike<{data:T|null;error:unknown}>){const {data,error}=await query;if(error)throw new ContentDataError();return data}

export interface ActionHubRepository{getTasks():Promise<Task[]>;getTask(id:string):Promise<Task|undefined>;getGuides():Promise<Guide[]>;getQuickLinks():Promise<QuickLink[]>;getTemplates():Promise<TextTemplate[]>;getMedia():Promise<MediaItem[]>;getVisualSettings():Promise<VisualSetting[]>;getVisualSetting(module:string):Promise<VisualSetting|undefined>}
export const repository:ActionHubRepository={
 async getTasks(){const db=await createClient();const rows=await run(db.from('tasks').select('*,task_steps(step_number,content)').eq('status','published').order('is_pinned',{ascending:false}).order('deadline',{ascending:true,nullsFirst:false}).order('urgency_score',{ascending:false}).order('required_score',{ascending:false}).order('sort_order'));return (rows??[]).map(row=>mapTask(row as TaskRow))},
 async getTask(id){const db=await createClient();const row=await run(db.from('tasks').select('*,task_steps(step_number,content)').eq('id',id).eq('status','published').maybeSingle());return row?mapTask(row as TaskRow):undefined},
 async getGuides(){const db=await createClient();const rows=await run(db.from('guides').select('*').eq('status','published').order('sort_order'));return (rows??[]).map((r)=>({id:r.id,type:r.guide_type,title:r.title,summary:r.summary??'',body:r.content,category:r.category??''}))},
 async getQuickLinks(){const db=await createClient();const rows=await run(db.from('quick_links').select('*').eq('is_enabled',true).order('sort_order'));return (rows??[]).map(r=>({id:r.id,title:r.title,platform:r.platform??'',url:r.external_url,icon:r.icon_key??'↗',sortOrder:r.sort_order,enabled:r.is_enabled}))},
 async getTemplates(){const db=await createClient();const rows=await run(db.from('text_templates').select('*').eq('is_enabled',true).order('is_pinned_today',{ascending:false}).order('sort_order'));return (rows??[]).map(r=>({id:r.id,title:r.title,type:r.template_type,content:r.content,pinned:r.is_pinned_today,sortOrder:r.sort_order,enabled:r.is_enabled}))},
 async getMedia(){const db=await createClient();const rows=await run(db.from('media_items').select('*').eq('is_enabled',true).order('published_at',{ascending:false}));return (rows??[]).map(r=>({id:r.id,title:r.title,category:r.category,publishedAt:r.published_at,coverUrl:r.cover_url??'',url:r.external_url,isNew:r.is_new,enabled:r.is_enabled}))},
 async getVisualSettings(){const db=await createClient();const rows=await run(db.from('visual_settings').select('*'));return (rows??[]).map(r=>({id:r.id,module:r.module_key,enabled:r.use_custom_background,imageUrl:r.background_url??'',position:r.background_position,size:r.background_size,overlay:Number(r.overlay_opacity),decorativeText:r.decorative_text??'',textEnabled:r.show_decorative_text}))},
 async getVisualSetting(module){return (await this.getVisualSettings()).find(x=>x.module===module)}
};
