/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {MobileNav} from '@/components/MobileNav';
import {TimezoneSync} from '@/components/TimezoneSync';
import {repository} from '@/lib/repository';
import {getUserDashboard} from '@/lib/user-repository';
import {visualStyle} from '@/lib/visual';
export const dynamic='force-dynamic';
const shortcuts=[['◷','我的任务记录','/me/tasks','累计行动记录'],['♙','我的账号','/me/account','平台账号数量'],['☆','我的收藏','#','收藏内容'],['▤','攻略 & Tips','/guide','攻略内容与小Tips'],['⚙','设置','/me/account','账号与偏好设置']];
function Avatar({url}:{url:string|null}){return <div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-full bg-[#dff1fb]">{url?<img src={url} alt="" className="h-full w-full object-cover" loading="lazy"/>:<span className="fish"/>}</div>}
export default async function Me(){
  const [setting,dashboard]=await Promise.all([repository.getVisualSetting('me'),getUserDashboard()]);const {user,profile,stats,leaderboard}=dashboard;const mine=leaderboard.find(row=>row.userId===user.id),top=leaderboard.slice(0,5).filter(row=>row.userId!==user.id),streak=stats.streak===null?'—':`${stats.streak}天`;
  return <main className="phone-shell me-page"><TimezoneSync current={profile.timezone}/><div className="page-pad pt-5"><section className="card me-profile-card mb-4 overflow-hidden"><div className="me-profile-visual p-5" style={visualStyle(setting)}><div className="me-profile-content flex items-center gap-3"><Avatar url={profile.avatar_url}/><div className="min-w-0 flex-1"><b className="block truncate text-lg">{profile.nickname}</b><span className="me-brand block mt-1">All for ZIYU</span></div><Link href="/me/account" className="pill no-underline">编辑资料</Link></div></div><div className="me-stats grid grid-cols-4 p-4 text-center">{[['今日行动',stats.today??'—'],['本周行动',stats.week??'—'],['连续养渝',streak],['累计行动',stats.total]].map(([label,value])=><div className="me-stat" key={label}><b className="block">{value}</b><span className="text-[10px] text-[#8096a9]">{label}</span></div>)}</div></section><section className="card mb-4 overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf2f6] p-4"><h2 className="me-section-title m-0 text-[15px]">养渝英雄榜 <span className="text-xs font-normal text-[#7890a6]">· 本周</span></h2><Link href="/me/leaderboard" className="text-xs font-semibold text-[#438bd1] no-underline">查看完整榜单 →</Link></div><div className="divide-y divide-[#edf2f6]">{mine?<div className="me-rank-row flex items-center gap-3 px-4 py-3"><b className="w-16 text-xs">我的排名 #{mine.rank}</b><Avatar url={mine.avatarUrl}/><span className="min-w-0 flex-1 truncate text-sm font-bold">{mine.nickname}</span><b className="text-sm">{mine.actionCount}次</b></div>:<div className="px-4 py-3 text-sm text-[#7890a6]">我的排名　暂未上榜</div>}{top.map(row=><div className="flex items-center gap-3 px-4 py-3" key={row.userId}><b className="w-8 text-sm">{row.rank<=3?['🥇','🥈','🥉'][row.rank-1]:row.rank}</b><Avatar url={row.avatarUrl}/><span className="min-w-0 flex-1 truncate text-sm font-bold">{row.nickname}</span><span className="text-sm">{row.actionCount}次</span></div>)}{!leaderboard.length&&<div className="px-4 py-4 text-sm text-[#7890a6]">本周暂无榜单数据</div>}</div></section><div className="grid grid-cols-2 gap-3">{shortcuts.map(([icon,label,href,subtitle],index)=><Link key={label} href={href} className={`card me-shortcut text-[#294663] no-underline ${index===4?'col-span-2':''}`}><span className="me-shortcut-icon" aria-hidden="true">{icon}</span><b className="block text-sm">{label}</b><span className="mt-1 block text-[11px] text-[#8298ac]">{subtitle}</span><span className="me-shortcut-chevron" aria-hidden="true">›</span></Link>)}</div></div><MobileNav/></main>;
}
