/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {MobileHeader} from '@/components/MobileHeader';
import {MobileNav} from '@/components/MobileNav';
import {TimezoneSync} from '@/components/TimezoneSync';
import {repository} from '@/lib/repository';
import {getUserDashboard} from '@/lib/user-repository';
import {visualStyle} from '@/lib/visual';
const entries=[['养渝英雄榜','/me/leaderboard'],['我的任务记录','/me/tasks'],['我的账号管理','/me/account'],['我的收藏','#'],['消息通知','#'],['设置','#']];
export const dynamic='force-dynamic';
export default async function Me(){const [setting,dashboard]=await Promise.all([repository.getVisualSetting('me'),getUserDashboard()]);const {user,profile,stats,accounts}=dashboard;const streak=stats.streak===null?'—':`${stats.streak}天`;return <main className="phone-shell" style={visualStyle(setting)}><TimezoneSync current={profile.timezone}/><MobileHeader title="我的养渝"/><div className="page-pad"><section className="card mb-5 overflow-hidden p-5"><div className="mb-4 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-full bg-[#dff1fb]">{profile.avatar_url?<><img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/></>:<span className="fish"/>}</div><div><b>{profile.nickname}</b><p className="m-0 text-xs text-[#8298ac]">{user.email}</p></div></div><div className="grid grid-cols-4 border-t border-[#eaf1f6] pt-4 text-center">{[['今日行动',stats.today??'—'],['本周行动',stats.week??'—'],['连续养渝',streak],['累计行动',stats.total]].map(([label,value])=><div key={label}><b className="block text-lg">{value}</b><span className="text-[10px] text-[#8096a9]">{label}</span></div>)}</div></section><div className="card overflow-hidden">{entries.map(([label,href],index)=><Link key={label} href={href} className={`flex items-center justify-between px-5 py-4 text-sm font-bold text-[#294663] no-underline ${index?'border-t border-[#edf2f6]':''}`}><span>{label}</span><span className="text-[#9eb0bf]">›</span></Link>)}</div><section className="card mt-5 p-5"><h2 className="mt-0 text-base">平台账号数量</h2>{accounts.length?accounts.map(account=><div key={account.platform} className="mt-3 flex items-center justify-between text-sm"><span>{account.platform}</span><b>{account.account_count}</b></div>):<p className="text-sm text-[#8aa0b2]">暂未设置平台账号数量</p>}<p className="mb-0 mt-4 text-[11px] leading-5 text-[#8aa0b2]">仅保存账号数量，不保存密码、Cookie 或第三方凭证。</p></section></div><MobileNav/></main>}
