/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {Suspense} from 'react';
import {MobileNav} from '@/components/MobileNav';
import {TimezoneSync} from '@/components/TimezoneSync';
import {getOrCreateOwnProfile,requireUserIdentity} from '@/lib/auth/user';
import {repository} from '@/lib/repository';
import {getCurrentLeaderboard,getUserStats,type UserStats} from '@/lib/user-repository';
import type {LeaderboardRow} from '@/lib/types';
import {visualStyle} from '@/lib/visual';
import './me.css';
export const dynamic='force-dynamic';
const shortcuts=[['◷','我的任务记录','/me/tasks','累计行动记录'],['♙','我的账号','/me/account','平台账号数量'],['☆','我的收藏','#','收藏内容'],['▤','攻略 & Tips','/guide','攻略内容与小Tips'],['⚙','设置','/me/account','账号与偏好设置']];
function Avatar({url,hero=false}:{url:string|null;hero?:boolean}){return <div className={`me-avatar grid shrink-0 place-items-center overflow-hidden rounded-full bg-[#dff1fb] ${hero?'is-hero':''}`}>{url?<img src={url} alt="" className="h-full w-full object-cover" loading="lazy"/>:<span className="fish"/>}</div>}
function Stats({stats}:{stats:UserStats}){const streak=stats.streak===null?'—':`${stats.streak}天`;return <div className="me-stats grid grid-cols-4 text-center">{[['今日行动',stats.today??'—'],['本周行动',stats.week??'—'],['连续养渝',streak],['累计行动',stats.total]].map(([label,value])=><div className="me-stat" key={label}><b className="block">{value}</b><span>{label}</span></div>)}</div>}
async function StreamingStats({data}:{data:Promise<UserStats>}){return <Stats stats={await data}/>}
function StatsFallback(){return <div className="me-stats grid grid-cols-4 text-center" aria-label="行动统计加载中">{['今日行动','本周行动','连续养渝','累计行动'].map(label=><div className="me-stat" key={label}><b className="mx-auto mb-1 block h-6 w-8 animate-pulse rounded bg-[#e4f0f6]"/><span>{label}</span></div>)}</div>}
function Leaderboard({rows,userId}:{rows:LeaderboardRow[];userId:string}){const mine=rows.find(row=>row.userId===userId),top=rows.slice(0,5).filter(row=>row.userId!==userId);return <section className="card me-leaderboard-card overflow-hidden"><div className="me-leaderboard-head flex items-center justify-between border-b border-[#edf2f6]"><h2 className="me-section-title m-0">养渝英雄榜 <span>· 本周</span></h2><Link href="/me/leaderboard" prefetch className="me-leaderboard-link no-underline">查看完整榜单 →</Link></div><div className="me-leaderboard-list divide-y divide-[#edf2f6]">{mine?<div className="me-rank-row flex items-center gap-3"><b className="me-own-rank">我的排名 #{mine.rank}</b><Avatar url={mine.avatarUrl}/><span className="min-w-0 flex-1 truncate font-semibold">{mine.nickname}</span><b className="me-action-count">{mine.actionCount}次</b></div>:<div className="me-empty-rank">我的排名　暂未上榜</div>}{top.map(row=><div className="me-leader-row flex items-center gap-3" key={row.userId}><b className={`me-rank-number rank-${row.rank}`}>{row.rank}</b><Avatar url={row.avatarUrl}/><span className="min-w-0 flex-1 truncate font-semibold">{row.nickname}</span><span className="me-action-count">{row.actionCount}次</span></div>)}{!rows.length&&<div className="me-empty-list">本周暂无榜单数据</div>}</div></section>}
async function StreamingLeaderboard({data,userId}:{data:Promise<LeaderboardRow[]>;userId:string}){return <Leaderboard rows={await data} userId={userId}/>}
function LeaderboardFallback(){return <section className="card me-leaderboard-card overflow-hidden" aria-label="本周榜单加载中"><div className="me-leaderboard-head flex items-center justify-between border-b border-[#edf2f6]"><h2 className="me-section-title m-0">养渝英雄榜 <span>· 本周</span></h2><span className="h-3 w-20 animate-pulse rounded bg-[#e4f0f6]"/></div><div className="space-y-px">{[1,2,3].map(row=><div className="me-leader-row flex items-center gap-3" key={row}><span className="h-5 w-8 animate-pulse rounded bg-[#e8f2f7]"/><span className="h-8 w-8 animate-pulse rounded-full bg-[#e8f2f7]"/><span className="h-3 flex-1 animate-pulse rounded bg-[#edf4f8]"/></div>)}</div></section>}
export default async function Me(){
  const settingPromise=repository.getVisualSetting('me');const context=await requireUserIdentity('/me');const profilePromise=getOrCreateOwnProfile(context);const statsPromise=getUserStats(context,profilePromise);const leaderboardPromise=getCurrentLeaderboard(context);const [setting,profile]=await Promise.all([settingPromise,profilePromise]);
  return <main className="phone-shell me-page"><TimezoneSync current={profile.timezone}/><div className="page-pad me-page-content"><section className="card me-profile-card overflow-hidden"><div className="me-profile-visual" style={visualStyle(setting)}><div className="me-profile-content flex items-center gap-3"><Avatar url={profile.avatar_url} hero/><div className="min-w-0 flex-1"><b className="me-profile-name block truncate">{profile.nickname}</b><span className="me-brand block">All for ZIYU</span></div><Link href="/me/account" prefetch className="me-edit-profile no-underline">编辑资料</Link></div></div><Suspense fallback={<StatsFallback/>}><StreamingStats data={statsPromise}/></Suspense></section><Suspense fallback={<LeaderboardFallback/>}><StreamingLeaderboard data={leaderboardPromise} userId={context.user.id}/></Suspense><div className="me-shortcut-grid grid grid-cols-2">{shortcuts.map(([icon,label,href,subtitle],index)=><Link key={label} href={href} prefetch={href==='#'?false:true} className={`card me-shortcut flex items-center text-[#294663] no-underline ${index===4?'col-span-2':''}`}><span className="me-shortcut-icon" aria-hidden="true">{icon}</span><span className="min-w-0 flex-1"><b className="block">{label}</b><span className="block truncate">{subtitle}</span></span><span className="me-shortcut-chevron" aria-hidden="true">›</span></Link>)}</div></div><MobileNav/></main>;
}
